= Welcome to Azure Architecture Starter Pack
:navtitle: Azure Architecture Starter Pack 


This is the automatic start page for version *{page-component-display-version} of Azure Architecture Starter Pack.

Azure Architecture Starter Pack is one of two documentation components in the Antora Demo.
The other docs component, Project Starter Pack, can be accessed using the component selector menu (aka component drawer) at the bottom of the menu on the left side of the page.

== Page source

This page is sourced from the AsciiDoc file name [.path]_index.adoc_ that is located at [.path]_azurearchitecturestarterpack/docs/modules/ROOT/pages_.

== Why is this the home page of Azure Architecture Starter Pack?

This page is automatically used as the start page of Azure Architecture Starter Pack because it is stored in the ROOT module and named [.path]_index.adoc_.

== Why is this the home page of the Antora Demo site?

This page is used as the home page for the Antora Demo because it is assigned as the site `start_page` in the Demo site's playbook file [.path]_site.yml_.

== Cross reference syntax to target this page

To create a cross reference *to this page from another page in the ROOT module of AzureArchitectureStarterPack*, the xref syntax would be `\xref:index.adoc[]`.

To create a cross reference *to this page from a page in Module One of AzureArchitectureStarterPack*, the xref syntax would be `\xref:ROOT:index.adoc[]`.

== Always target the latest version of this page

To create a cross reference *to the latest version of this page from a page in ProjectStarterPack*, the xref syntax would be `\xref:azurearchitecturestarterpack::index.adoc`.

== Target a specific version of this page

To create a cross reference *to version 1.0 of this page from a page in ProjectStarterPack*, the xref syntax would be `\xref:1.0@azurearchitecturestarterpack::index.adoc[]`
